In [1]:
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import os
from torchvision import transforms
import cv2
from torch.utils.tensorboard import SummaryWriter

通过transforms.ToTensor解决两个问题   
1.transforms如何使用   
2.Tensor数据类型相较于普通图片数据类型有何不同   

In [2]:
img_path = "../data/train/ants_image/0013035.jpg"
# Image读取到的是PIL类型
img = Image.open(img_path)
print(img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=768x512 at 0x107365EB0>


In [3]:
# cv2读取到的数据是numpy类型
cv_img = cv2.imread(img_path)
print(cv_img)

[[[233 151  80]
  [233 151  80]
  [233 151  80]
  ...
  [234 152  81]
  [232 150  79]
  [229 147  76]]

 [[234 152  81]
  [234 152  81]
  [234 152  81]
  ...
  [234 152  81]
  [232 150  79]
  [229 147  76]]

 [[235 153  82]
  [235 153  82]
  [235 153  82]
  ...
  [233 151  80]
  [232 150  79]
  [230 148  77]]

 ...

 [[237 160  87]
  [237 160  87]
  [236 159  86]
  ...
  [141  92  44]
  [235 158  95]
  [228 157  90]]

 [[237 160  87]
  [237 160  87]
  [236 159  86]
  ...
  [226 147  84]
  [255 160  90]
  [233 152  84]]

 [[237 160  87]
  [237 160  87]
  [236 159  86]
  ...
  [242 160  79]
  [250 159  78]
  [233 161  84]]]


In [4]:
# 1.Tensor数据类型相较于普通图片数据类型有何不同？为什么需要Tensor
# 自行百度

In [5]:
# 2.transforms如何使用
# 将其赋予一个变量，该变量就成为了一个可以处理其他图片的对象，可以理解为下面这样：
# tool = transforms.ToTensor()
# result = tool(input)
trans_tensor = transforms.ToTensor()
tensor_img = trans_tensor(img)

print(tensor_img)

tensor([[[0.3137, 0.3137, 0.3137,  ..., 0.3176, 0.3098, 0.2980],
         [0.3176, 0.3176, 0.3176,  ..., 0.3176, 0.3098, 0.2980],
         [0.3216, 0.3216, 0.3216,  ..., 0.3137, 0.3098, 0.3020],
         ...,
         [0.3412, 0.3412, 0.3373,  ..., 0.1725, 0.3725, 0.3529],
         [0.3412, 0.3412, 0.3373,  ..., 0.3294, 0.3529, 0.3294],
         [0.3412, 0.3412, 0.3373,  ..., 0.3098, 0.3059, 0.3294]],

        [[0.5922, 0.5922, 0.5922,  ..., 0.5961, 0.5882, 0.5765],
         [0.5961, 0.5961, 0.5961,  ..., 0.5961, 0.5882, 0.5765],
         [0.6000, 0.6000, 0.6000,  ..., 0.5922, 0.5882, 0.5804],
         ...,
         [0.6275, 0.6275, 0.6235,  ..., 0.3608, 0.6196, 0.6157],
         [0.6275, 0.6275, 0.6235,  ..., 0.5765, 0.6275, 0.5961],
         [0.6275, 0.6275, 0.6235,  ..., 0.6275, 0.6235, 0.6314]],

        [[0.9137, 0.9137, 0.9137,  ..., 0.9176, 0.9098, 0.8980],
         [0.9176, 0.9176, 0.9176,  ..., 0.9176, 0.9098, 0.8980],
         [0.9216, 0.9216, 0.9216,  ..., 0.9137, 0.9098, 0.

In [6]:
writer = SummaryWriter("../logs/3_Transforms")
# writer.add_image("Tensor_img", tensor_img)
# writer.close()

In [7]:
# 常见Transfoms中的工具的使用
# 重点关注：
# 输入、输出、作用

img_path = "../imgs/test.png"
# Image读取到的是PIL类型
img = Image.open(img_path)
# print(img)

In [8]:
# ToTensor:Convert a PIL Image or ndarray to tensor and scale the values accordingly
# 将其他类型转换为Tensor类型
trans_totensor = transforms.ToTensor()
img_tensor = trans_totensor(img)
writer.add_image("ToTensor", img_tensor)

In [9]:
# Normalize:Normalize a tensor image with mean and standard deviation
# 将tensor类型进行归一化（通过均值和标准差）
# 作用：改变图片中的一些值，使图片更加契合后面要进入的网络
# 举例：input[0, 1],使用mean[0.5], std[0.5]经过计算公式后就成了output[-1, 1]
# 计算公式：output[channel] = (input[channel] - mean[channel]) / std[channel]
    # Args:
    #     mean (sequence): Sequence of means for each channel.
    #     std (sequence): Sequence of standard deviations for each channel.
    #     mean和std需要根据图片的信道来进行填充，eg：RGB图片为三通道，PNG为四通道
    #     inplace(bool,optional): Bool to make this operation in-place.     默认为False
print(img_tensor[0][0][0])
trans_norm = transforms.Normalize([0.5, 0.5, 0.5, 0.5], [0.5, 0.5, 0.5, 0.5]) 
img_norm = trans_norm(img_tensor)
print(img_norm[0][0][0])
writer.add_image("Normalize", img_norm)

tensor(0.7882)
tensor(0.5765)


In [10]:
# Resize:Resize the input image to the given size
# 将传入的图像进行尺寸缩放
# Args:
#         size (sequence or int): Desired output size. If size is a sequence like
#             (h, w), output size will be matched to this. If size is an int,
#             smaller edge of the image will be matched to this number.
#             i.e, if height > width, then image will be rescaled to
#             (size * height / width, size).
print(img_tensor.shape)
trans_resize = transforms.Resize((512, 512))
img_resize = trans_resize(img_tensor)
print(img_resize)
print(img_resize.shape)
writer.add_image("Resize", img_resize)

torch.Size([4, 1800, 3200])
tensor([[[0.8008, 0.8183, 0.8183,  ..., 0.1188, 0.1202, 0.1241],
         [0.6520, 0.8126, 0.8218,  ..., 0.0894, 0.0933, 0.0955],
         [0.3291, 0.7746, 0.8064,  ..., 0.0034, 0.0027, 0.0036],
         ...,
         [0.1096, 0.2304, 0.2316,  ..., 0.1141, 0.1136, 0.1141],
         [0.1130, 0.2307, 0.2317,  ..., 0.1137, 0.1137, 0.1137],
         [0.1136, 0.2308, 0.2318,  ..., 0.1137, 0.1137, 0.1137]],

        [[0.2769, 0.2739, 0.2757,  ..., 0.2092, 0.2092, 0.2080],
         [0.2322, 0.2725, 0.2722,  ..., 0.1460, 0.1425, 0.1409],
         [0.1314, 0.2770, 0.2751,  ..., 0.0049, 0.0042, 0.0048],
         ...,
         [0.1279, 0.3019, 0.3059,  ..., 0.2075, 0.2076, 0.2074],
         [0.1296, 0.3028, 0.3056,  ..., 0.2078, 0.2078, 0.2078],
         [0.1305, 0.3029, 0.3057,  ..., 0.2078, 0.2078, 0.2078]],

        [[0.2105, 0.2042, 0.1889,  ..., 0.2368, 0.2334, 0.2336],
         [0.1819, 0.2008, 0.1949,  ..., 0.1666, 0.1655, 0.1656],
         [0.1171, 0.2176, 0.20

In [11]:
# Compose:Composes several transforms together
# 将多个Transforms的工具整合到一起，一次调用，方便使用
    # Example:
    #     >>> transforms.Compose([
    #     >>>     transforms.CenterCrop(10),
    #     >>>     transforms.PILToTensor(),
    #     >>>     transforms.ConvertImageDtype(torch.float),
    #     >>> ])

# 这里将前面的几种变化结合起来:ToTensor,Normalize,Resize
trans_compose = transforms.Compose([
    trans_tensor,
    trans_norm,
    trans_resize,
])
img_compose = trans_compose(img)
writer.add_image("Compose", img_compose)

In [12]:
# RandomCrop:Crop the given image at a random location
    # Args:
    #     size (sequence or int): Desired output size of the crop. If size is an
    #         int instead of sequence like (h, w), a square crop (size, size) is
    #         made. If provided a sequence of length 1, it will be interpreted as (size[0], size[0]).
    #     padding (int or sequence, optional): Optional padding on each border
    #         of the image. Default is None. If a single int is provided this
    #         is used to pad all borders. If sequence of length 2 is provided this is the padding
    #         on left/right and top/bottom respectively. If a sequence of length 4 is provided
    #         this is the padding for the left, top, right and bottom borders respectively.

    #         .. note::
    #             In torchscript mode padding as single int is not supported, use a sequence of
    #             length 1: ``[padding, ]``.
    #     pad_if_needed (boolean): It will pad the image if smaller than the
    #         desired size to avoid raising an exception. Since cropping is done
    #         after padding, the padding seems to be done at a random offset.
    #     fill (number or tuple): Pixel fill value for constant fill. Default is 0. If a tuple of
    #         length 3, it is used to fill R, G, B channels respectively.
    #         This value is only used when the padding_mode is constant.
    #         Only number is supported for torch Tensor.
    #         Only int or tuple value is supported for PIL Image.
    #     padding_mode (str): Type of padding. Should be: constant, edge, reflect or symmetric.
    #         Default is constant.

    #         - constant: pads with a constant value, this value is specified with fill

    #         - edge: pads with the last value at the edge of the image.
    #           If input a 5D torch Tensor, the last 3 dimensions will be padded instead of the last 2

    #         - reflect: pads with reflection of image without repeating the last value on the edge.
    #           For example, padding [1, 2, 3, 4] with 2 elements on both sides in reflect mode
    #           will result in [3, 2, 1, 2, 3, 4, 3, 2]

    #         - symmetric: pads with reflection of image repeating the last value on the edge.
    #           For example, padding [1, 2, 3, 4] with 2 elements on both sides in symmetric mode
    #           will result in [2, 1, 1, 2, 3, 4, 4, 3]

    # 参数有点多，其他都有默认值一般不用管，一般只需要第一个size
    # size:和resize不同，(h, w)是按照高和宽来进行裁剪,如果是单个数字x则会裁剪为边长为x的正方形
trans_randomcrop_1 = transforms.RandomCrop(512)
trans_randomcrop_2 = transforms.RandomCrop((180, 320))

for i in range(100):
    img_randomcrop = trans_randomcrop_1(img_tensor)
    writer.add_image("RandomCrop1", img_randomcrop, i)
    img_randomcrop = trans_randomcrop_2(img_tensor)
    writer.add_image("RandomCrop2", img_randomcrop, i)

In [13]:
writer.close()

In [ ]:
# 关注输入输出
# 多看官方文档

# 不知道返回类型的时候
# print()
# print(type())
# debug