In [1]:
# DataLoader常见参数设置
# dataset (Dataset) – dataset from which to load the data.
# batch_size (int, optional) – how many samples per batch to load (default: 1).
# shuffle (bool, optional) – True:打乱    False:不打乱    (default: False)
# sampler (Sampler or Iterable, optional) – 采样策略
    # sampler 决定每个 epoch 中 DataLoader 返回数据的顺序。
	# •	不设置 sampler，且 shuffle=True → 系统默认用 RandomSampler
	# •	设置了 sampler → 你自己决定样本顺序，就不能再设置 shuffle（会冲突）
    # PyTorch 已经有一些常用的 sampler 实现：
        # SequentialSampler:按顺序依次采样（适用于验证或不打乱的训练,默认在 shuffle = False 时使用）
        # RandomSampler:随机打乱后采样（适用于训练时打乱数据,默认在 shuffle = True 时使用）
        # WeightedRandomSampler:根据给定权重概率进行有放回采样（适用于类别不平衡问题)
        # SubsetRandomSampler:从指定的索引子集中随机采样（适用于划分训练/验证集等情况）
# num_workers (int, optional) – how many subprocesses to use for data loading. 0 means that the data will be loaded in the main process. (default: 0)          # 用于数据加载的子进程（subprocesses）数量
# drop_last (bool, optional) – 是否舍弃不足一组 batch_size 的数据
    # set to True to drop the last incomplete batch, if the dataset size is not divisible by the batch size. If False and the size of dataset is not divisible by the batch size, then the last batch will be smaller. (default: False)

In [15]:
import torchvision
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

In [8]:
# 准备测试集
test_data = torchvision.datasets.CIFAR10("../datasets/CIFAR10", train = False, transform = torchvision.transforms.ToTensor())
# 测试数据集中第一张图片及其target
# datasets的__getitem__(index: int)会return 给予index的 img, target
img, target = test_data[0]
print(img.shape)
print(target)

torch.Size([3, 32, 32])
3


In [17]:
test_loader = DataLoader(dataset = test_data, batch_size = 4, shuffle = True, num_workers = 0, drop_last = False)
# DataLoader每次读取会以取出datasets中的batch_size个数据，分别将img和target打包返回
writer = SummaryWriter("../logs/5_DataLoader")
step = 0
for data in test_loader:
    if step > 10:
        break
    print(step, ":")
    imgs, targets = data
    writer.add_images("test_data", imgs, step)
    print(imgs.shape)
    print(targets)
    step += 1

writer.close()

11 :
torch.Size([4, 3, 32, 32])
tensor([5, 8, 0, 0])
11 :
torch.Size([4, 3, 32, 32])
tensor([9, 0, 4, 4])
11 :
torch.Size([4, 3, 32, 32])
tensor([6, 1, 8, 9])
11 :
torch.Size([4, 3, 32, 32])
tensor([6, 4, 6, 1])
11 :
torch.Size([4, 3, 32, 32])
tensor([0, 5, 0, 5])
11 :
torch.Size([4, 3, 32, 32])
tensor([7, 7, 7, 3])
11 :
torch.Size([4, 3, 32, 32])
tensor([9, 1, 7, 4])
11 :
torch.Size([4, 3, 32, 32])
tensor([1, 5, 2, 8])
11 :
torch.Size([4, 3, 32, 32])
tensor([8, 0, 5, 1])
11 :
torch.Size([4, 3, 32, 32])
tensor([2, 8, 9, 9])
11 :
torch.Size([4, 3, 32, 32])
tensor([1, 5, 3, 4])
